# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Transform(object):
    def setupUi(self, Transform):
        Transform.setObjectName("Transform")
        Transform.resize(400, 300)
        self.buttonBox = QtWidgets.QDialogButtonBox(Transform)
        self.buttonBox.setGeometry(QtCore.QRect(30, 240, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.lineEdit = QtWidgets.QLineEdit(Transform)
        self.lineEdit.setGeometry(QtCore.QRect(30, 140, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(Transform)
        self.lineEdit_2.setGeometry(QtCore.QRect(30, 40, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(Transform)
        self.lineEdit_3.setGeometry(QtCore.QRect(30, 90, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.RotatespinBox = QtWidgets.QSpinBox(Transform)
        self.RotatespinBox.setGeometry(QtCore.QRect(100, 140, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.RotatespinBox.setFont(font)
        self.RotatespinBox.setMinimum(-45)
        self.RotatespinBox.setMaximum(45)
        self.RotatespinBox.setSingleStep(5)
        self.RotatespinBox.setObjectName("RotatespinBox")
        self.ScaleSpinBox = QtWidgets.QDoubleSpinBox(Transform)
        self.ScaleSpinBox.setGeometry(QtCore.QRect(100, 40, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ScaleSpinBox.setFont(font)
        self.ScaleSpinBox.setDecimals(1)
        self.ScaleSpinBox.setMinimum(0.5)
        self.ScaleSpinBox.setMaximum(1.5)
        self.ScaleSpinBox.setSingleStep(0.1)
        self.ScaleSpinBox.setProperty("value", 1.0)
        self.ScaleSpinBox.setObjectName("ScaleSpinBox")
        self.TranslateSpinBox = QtWidgets.QDoubleSpinBox(Transform)
        self.TranslateSpinBox.setGeometry(QtCore.QRect(100, 90, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.TranslateSpinBox.setFont(font)
        self.TranslateSpinBox.setDecimals(1)
        self.TranslateSpinBox.setMinimum(0.0)
        self.TranslateSpinBox.setMaximum(0.5)
        self.TranslateSpinBox.setSingleStep(0.1)
        self.TranslateSpinBox.setProperty("value", 0.0)
        self.TranslateSpinBox.setObjectName("TranslateSpinBox")
        self.lineEdit_4 = QtWidgets.QLineEdit(Transform)
        self.lineEdit_4.setGeometry(QtCore.QRect(230, 40, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_4.setFont(font)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.BrightspinBox = QtWidgets.QSpinBox(Transform)
        self.BrightspinBox.setGeometry(QtCore.QRect(300, 40, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.BrightspinBox.setFont(font)
        self.BrightspinBox.setMinimum(-32)
        self.BrightspinBox.setMaximum(32)
        self.BrightspinBox.setSingleStep(2)
        self.BrightspinBox.setObjectName("BrightspinBox")
        self.lineEdit_5 = QtWidgets.QLineEdit(Transform)
        self.lineEdit_5.setGeometry(QtCore.QRect(210, 90, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_5.setFont(font)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.line = QtWidgets.QFrame(Transform)
        self.line.setGeometry(QtCore.QRect(180, 20, 20, 191))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.lineEdit_6 = QtWidgets.QLineEdit(Transform)
        self.lineEdit_6.setGeometry(QtCore.QRect(210, 140, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_6.setFont(font)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.ContrastSpinBox = QtWidgets.QDoubleSpinBox(Transform)
        self.ContrastSpinBox.setGeometry(QtCore.QRect(300, 90, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ContrastSpinBox.setFont(font)
        self.ContrastSpinBox.setDecimals(1)
        self.ContrastSpinBox.setMinimum(0.5)
        self.ContrastSpinBox.setMaximum(1.5)
        self.ContrastSpinBox.setSingleStep(0.1)
        self.ContrastSpinBox.setProperty("value", 1.0)
        self.ContrastSpinBox.setObjectName("ContrastSpinBox")
        self.GammaSpinBox = QtWidgets.QDoubleSpinBox(Transform)
        self.GammaSpinBox.setGeometry(QtCore.QRect(300, 140, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.GammaSpinBox.setFont(font)
        self.GammaSpinBox.setDecimals(1)
        self.GammaSpinBox.setMinimum(0.5)
        self.GammaSpinBox.setMaximum(1.5)
        self.GammaSpinBox.setSingleStep(0.1)
        self.GammaSpinBox.setProperty("value", 1.0)
        self.GammaSpinBox.setObjectName("GammaSpinBox")

        self.retranslateUi(Transform)
        self.buttonBox.accepted.connect(Transform.accept)
        self.buttonBox.rejected.connect(Transform.reject)
        QtCore.QMetaObject.connectSlotsByName(Transform)

    def retranslateUi(self, Transform):
        _translate = QtCore.QCoreApplication.translate
        Transform.setWindowTitle(_translate("Transform", "Dialog"))
        self.lineEdit.setText(_translate("Transform", "旋转"))
        self.lineEdit_2.setText(_translate("Transform", "缩放"))
        self.lineEdit_3.setText(_translate("Transform", "平移"))
        self.lineEdit_4.setText(_translate("Transform", "亮度"))
        self.lineEdit_5.setText(_translate("Transform", "对比度"))
        self.lineEdit_6.setText(_translate("Transform", "伽马值"))

